### ISSUE TITLE
Smoke Test Dresser 23M results 

### ISSUE THREAD

**Issue by Wleveill** [mcquaiga/EvcProver#221]
Hey Adam, performed smoke test on two provers and the 23M results are failing. Results are -0.22% and -0.25% We may not have adjusted the required pulse counts on that size.

**Comment by mcquaiga** [comment]
Do you remember how to change the target uncorrected pulses for that meter type?

In the folder ItemDefinitions, open meter types.json

**Comment by Wleveill** [comment]
Yep Thanks
